apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-app
  template:
    metadata:
      labels:
        app: go-app
    spec:
      nodeSelector:
        "kubernetes.io/os": linux
      containers:
      - name: go-app
        image: abhiacreastus.azurecr.io/my-go-app