apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: "2023-10-23T19:10:44Z"
  generation: 1
  labels:
    gatekeeper.sh/constraint: "yes"
    managed-by: azure-policy-addon
  name: k8sazurev1blocknakedpods.constraints.gatekeeper.sh
  ownerReferences:
  - apiVersion: templates.gatekeeper.sh/v1beta1
    blockOwnerDeletion: true
    controller: true
    kind: ConstraintTemplate
    name: k8sazurev1blocknakedpods
    uid: cd11e99c-7529-4f6f-9051-993bed1da348
  resourceVersion: "4288"
  uid: 6fc072c2-b7c6-4e69-a6a4-c1de2add233d
spec:
  conversion:
    strategy: None
  group: constraints.gatekeeper.sh
  names:
    categories:
    - constraint
    - constraints
    kind: K8sAzureV1BlockNakedPods
    listKind: K8sAzureV1BlockNakedPodsList
    plural: k8sazurev1blocknakedpods
    singular: k8sazurev1blocknakedpods
  scope: Cluster
  versions:
  - additionalPrinterColumns:
    - description: Type of enforcement action
      jsonPath: .spec.enforcementAction
      name: enforcement-action
      type: string
    - description: Total number of violations
      jsonPath: .status.totalViolations
      name: total-violations
      type: integer
    name: v1beta1
    schema:
      openAPIV3Schema:
        properties:
          metadata:
            properties:
              name:
                maxLength: 63
                type: string
            type: object
          spec:
            properties:
              enforcementAction:
                type: string
              match:
                properties:
                  excludedNamespaces:
                    description: '`excludedNamespaces` is a list of namespace names.
                      If defined, a constraint only applies to resources not in a
                      listed namespace. ExcludedNamespaces also supports a prefix-based
                      glob.  For example, `excludedNamespaces: [kube-*]` matches both
                      `kube-system` and `kube-public`.'
                    items:
                      pattern: ^(\*|\*-)?[a-z0-9]([-a-z0-9]*[a-z0-9])?(\*|-\*)?$
                      type: string
                    type: array
                  kinds:
                    items:
                      description: The Group and Kind of objects that should be matched.  If
                        multiple groups/kinds combinations are specified, an incoming
                        resource need only match one to be in scope.
                      properties:
                        apiGroups:
                          items:
                            nullable: true
                            type: string
                          type: array
                        kinds:
                          items:
                            nullable: true
                            type: string
                          type: array
                      type: object
                    type: array
                  labelSelector:
                    description: '`labelSelector` is the combination of two optional
                      fields: `matchLabels` and `matchExpressions`.  These two fields
                      provide different methods of selecting or excluding k8s objects
                      based on the label keys and values included in object metadata.  All
                      selection expressions from both sections are ANDed to determine
                      if an object meets the cumulative requirements of the selector.'
                    properties:
                      matchExpressions:
                        description: a list of label selection expressions. A selected
                          resource will match all of these expressions.
                        items:
                          description: a selector that specifies a label key, a set
                            of label values, an operator that defines the relationship
                            between the two that will match the selector.
                          properties:
                            key:
                              description: the label key that the selector applies
                                to.
                              type: string
                            operator:
                              description: the relationship between the label and
                                value set that defines a matching selection.
                              enum:
                              - In
                              - NotIn
                              - Exists
                              - DoesNotExist
                              type: string
                            values:
                              description: a set of label values.
                              items:
                                type: string
                              type: array
                          type: object
                        type: array
                      matchLabels:
                        additionalProperties:
                          type: string
                        description: A mapping of label keys to sets of allowed label
                          values for those keys.  A selected resource will match all
                          of these expressions.
                        type: object
                        x-kubernetes-preserve-unknown-fields: true
                    type: object
                  name:
                    description: '`name` is the name of an object.  If defined, it
                      matches against objects with the specified name.  Name also
                      supports a prefix-based glob.  For example, `name: pod-*` matches
                      both `pod-a` and `pod-b`.'
                    pattern: ^(\*|\*-)?[a-z0-9]([-a-z0-9]*[a-z0-9])?(\*|-\*)?$
                    type: string
                  namespaceSelector:
                    description: '`namespaceSelector` is a label selector against
                      an object''s containing namespace or the object itself, if the
                      object is a namespace.'
                    properties:
                      matchExpressions:
                        description: a list of label selection expressions. A selected
                          resource will match all of these expressions.
                        items:
                          description: a selector that specifies a label key, a set
                            of label values, an operator that defines the relationship
                            between the two that will match the selector.
                          properties:
                            key:
                              description: the label key that the selector applies
                                to.
                              type: string
                            operator:
                              description: the relationship between the label and
                                value set that defines a matching selection.
                              enum:
                              - In
                              - NotIn
                              - Exists
                              - DoesNotExist
                              type: string
                            values:
                              description: a set of label values.
                              items:
                                type: string
                              type: array
                          type: object
                        type: array
                      matchLabels:
                        additionalProperties:
                          type: string
                        description: A mapping of label keys to sets of allowed label
                          values for those keys.  A selected resource will match all
                          of these expressions.
                        type: object
                        x-kubernetes-preserve-unknown-fields: true
                    type: object
                  namespaces:
                    description: '`namespaces` is a list of namespace names. If defined,
                      a constraint only applies to resources in a listed namespace.  Namespaces
                      also supports a prefix-based glob.  For example, `namespaces:
                      [kube-*]` matches both `kube-system` and `kube-public`.'
                    items:
                      pattern: ^(\*|\*-)?[a-z0-9]([-a-z0-9]*[a-z0-9])?(\*|-\*)?$
                      type: string
                    type: array
                  scope:
                    description: '`scope` determines if cluster-scoped and/or namespaced-scoped
                      resources are matched.  Accepts `*`, `Cluster`, or `Namespaced`.
                      (defaults to `*`)'
                    enum:
                    - '*'
                    - Cluster
                    - Namespaced
                    type: string
                type: object
              parameters:
                x-kubernetes-preserve-unknown-fields: true
            type: object
          status:
            x-kubernetes-preserve-unknown-fields: true
        type: object
    served: true
    storage: true
    subresources:
      status: {}
  - additionalPrinterColumns:
    - description: Type of enforcement action
      jsonPath: .spec.enforcementAction
      name: enforcement-action
      type: string
    - description: Total number of violations
      jsonPath: .status.totalViolations
      name: total-violations
      type: integer
    name: v1alpha1
    schema:
      openAPIV3Schema:
        properties:
          metadata:
            properties:
              name:
                maxLength: 63
                type: string
            type: object
          spec:
            properties:
              enforcementAction:
                type: string
              match:
                properties:
                  excludedNamespaces:
                    description: '`excludedNamespaces` is a list of namespace names.
                      If defined, a constraint only applies to resources not in a
                      listed namespace. ExcludedNamespaces also supports a prefix-based
                      glob.  For example, `excludedNamespaces: [kube-*]` matches both
                      `kube-system` and `kube-public`.'
                    items:
                      pattern: ^(\*|\*-)?[a-z0-9]([-a-z0-9]*[a-z0-9])?(\*|-\*)?$
                      type: string
                    type: array
                  kinds:
                    items:
                      description: The Group and Kind of objects that should be matched.  If
                        multiple groups/kinds combinations are specified, an incoming
                        resource need only match one to be in scope.
                      properties:
                        apiGroups:
                          items:
                            nullable: true
                            type: string
                          type: array
                        kinds:
                          items:
                            nullable: true
                            type: string
                          type: array
                      type: object
                    type: array
                  labelSelector:
                    description: '`labelSelector` is the combination of two optional
                      fields: `matchLabels` and `matchExpressions`.  These two fields
                      provide different methods of selecting or excluding k8s objects
                      based on the label keys and values included in object metadata.  All
                      selection expressions from both sections are ANDed to determine
                      if an object meets the cumulative requirements of the selector.'
                    properties:
                      matchExpressions:
                        description: a list of label selection expressions. A selected
                          resource will match all of these expressions.
                        items:
                          description: a selector that specifies a label key, a set
                            of label values, an operator that defines the relationship
                            between the two that will match the selector.
                          properties:
                            key:
                              description: the label key that the selector applies
                                to.
                              type: string
                            operator:
                              description: the relationship between the label and
                                value set that defines a matching selection.
                              enum:
                              - In
                              - NotIn
                              - Exists
                              - DoesNotExist
                              type: string
                            values:
                              description: a set of label values.
                              items:
                                type: string
                              type: array
                          type: object
                        type: array
                      matchLabels:
                        additionalProperties:
                          type: string
                        description: A mapping of label keys to sets of allowed label
                          values for those keys.  A selected resource will match all
                          of these expressions.
                        type: object
                        x-kubernetes-preserve-unknown-fields: true
                    type: object
                  name:
                    description: '`name` is the name of an object.  If defined, it
                      matches against objects with the specified name.  Name also
                      supports a prefix-based glob.  For example, `name: pod-*` matches
                      both `pod-a` and `pod-b`.'
                    pattern: ^(\*|\*-)?[a-z0-9]([-a-z0-9]*[a-z0-9])?(\*|-\*)?$
                    type: string
                  namespaceSelector:
                    description: '`namespaceSelector` is a label selector against
                      an object''s containing namespace or the object itself, if the
                      object is a namespace.'
                    properties:
                      matchExpressions:
                        description: a list of label selection expressions. A selected
                          resource will match all of these expressions.
                        items:
                          description: a selector that specifies a label key, a set
                            of label values, an operator that defines the relationship
                            between the two that will match the selector.
                          properties:
                            key:
                              description: the label key that the selector applies
                                to.
                              type: string
                            operator:
                              description: the relationship between the label and
                                value set that defines a matching selection.
                              enum:
                              - In
                              - NotIn
                              - Exists
                              - DoesNotExist
                              type: string
                            values:
                              description: a set of label values.
                              items:
                                type: string
                              type: array
                          type: object
                        type: array
                      matchLabels:
                        additionalProperties:
                          type: string
                        description: A mapping of label keys to sets of allowed label
                          values for those keys.  A selected resource will match all
                          of these expressions.
                        type: object
                        x-kubernetes-preserve-unknown-fields: true
                    type: object
                  namespaces:
                    description: '`namespaces` is a list of namespace names. If defined,
                      a constraint only applies to resources in a listed namespace.  Namespaces
                      also supports a prefix-based glob.  For example, `namespaces:
                      [kube-*]` matches both `kube-system` and `kube-public`.'
                    items:
                      pattern: ^(\*|\*-)?[a-z0-9]([-a-z0-9]*[a-z0-9])?(\*|-\*)?$
                      type: string
                    type: array
                  scope:
                    description: '`scope` determines if cluster-scoped and/or namespaced-scoped
                      resources are matched.  Accepts `*`, `Cluster`, or `Namespaced`.
                      (defaults to `*`)'
                    enum:
                    - '*'
                    - Cluster
                    - Namespaced
                    type: string
                type: object
              parameters:
                x-kubernetes-preserve-unknown-fields: true
            type: object
          status:
            x-kubernetes-preserve-unknown-fields: true
        type: object
    served: true
    storage: false
    subresources:
      status: {}
status:
  acceptedNames:
    categories:
    - constraint
    - constraints
    kind: K8sAzureV1BlockNakedPods
    listKind: K8sAzureV1BlockNakedPodsList
    plural: k8sazurev1blocknakedpods
    singular: k8sazurev1blocknakedpods
  conditions:
  - lastTransitionTime: "2023-10-23T19:10:44Z"
    message: no conflicts found
    reason: NoConflicts
    status: "True"
    type: NamesAccepted
  - lastTransitionTime: "2023-10-23T19:10:45Z"
    message: the initial names have been accepted
    reason: InitialNamesAccepted
    status: "True"
    type: Established
  storedVersions:
  - v1beta1