apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sRequiredLabels
metadata:
 name: all-pods-must-have-owner
spec:
  match:
    kinds:
    - apiGroups: [""]
      kinds: ["Pod"]
  parameters:
    message: "all pods must have an owner label that has your usename"
    labels:
      - key: owner
        allowedRegex: "^[a-zA-Z]+.example.org$"