name: kubesec test

on:
 workflow_dispatch:

jobs:
 scan:
  runs-on: ubuntu-latest
  permissions:
   security-events: write
  steps:
   - name: checkout code
     uses: actions/checkout@v2
   - name: Get sarif.tpl
     run: wget https://raw.githubusercontent.com/bsanchezmir/kubesec-action/main/sarif.tpl

   - name: Run kubesec scanner
     uses: bsanchezmir/kubesec-action@latest
     with:
          filename: go-pods.yaml
          exit-code: "0"
          format: template
          template: ./sarif.tpl
          output: kubesec-results.sarif

   - name: Upload Kubesec scan results to GitHub Security tab
     uses: github/codeql-action/upload-sarif@v2
     with:
          sarif_file: kubesec-results.sarif
